#!/bin/bash

firstd=0
dcount=${1:-1}
dsize=${2:-100}
dfspath=$3
systemid=$4

if [ -z "$dfspath" ] ; then
   dfspath=/data/dfs
fi

if [ -z "$systemid" ] ; then
   systemid=`wxgetconfig -s`
fi

dsbytes_pre=$(($dsize * 1024 * 1024 * 1024))
dssectors=$(( ($dsbytes_pre + 511) / 512))
dsbytes=$(($dssectors * 512))

ct=$firstd
dtop=$(($firstd + $dcount))

dlist=

while [ "$ct" -lt "$dtop" ] ; do
      echo "Creating volume $ct"
      fn=${dfspath}/disk${ct}
      rm -f $fn
      dd if=/dev/zero of=$fn seek=$(($dsbytes - 1)) count=1 bs=1 >&/dev/null
      /opt/kognitio/wx2/current/software/Linux64/wxdiskid -C -s ${systemid} -u NEW_DISK_${ct} -N ${dssectors} -z -p $fn

      if [ -z "$dlist" ] ; then
         dlist=$fn
      else
         dlist="$dlist,$fn"
      fi

      ct=$(($ct + 1))
done

wxconftool -G '{all}' -s system -a "disks=$dlist" -W

wxserver smd all restart

