#!/bin/bash

if [ -f /data/config/config ] ; then
    cp -p /data/config/config /opt/kognitio/wx2/etc
    cp -p /data/config/secret /opt/kognitio/wx2/etc
    cp -f /data/config/*.wxli /opt/kognitio/wx2/licenses
    wxsvc start
else
    /opt/kognitio/scripts/set-data-owner      # make sure the proper ownership is on /data so we can create things later
fi

while [ 1 ] ; do
    sleep 3600    # we don't need to do anything here.  Just keep the container alive
done
