#!/bin/bash

# helper to size memory based on cgroup limits or memsize

memkbs=`grep MemTotal /proc/meminfo | awk '{print $2}'`
mem=$(($memkbs * 1024))

cgm=`cgget -n --values-only --variable memory.limit_in_bytes /`
if [ -n "$cgm" ] && [ "$cgm" -lt "$mem" ] ; then
   echo "$cgm"
else
   echo "$mem"
fi
